### ISSUE TITLE
챕터5 > Analyzer.py error

### ISSUE THREAD

**Issue by woo9904** [INVESTAR/StockAnalysisInPython#10]
안녕하세요 하나하나 코드 작성하다가 에러가 발생해, 예제 코드를 사용해도 안돼, 질문올립니다. 

262pg의 EfficientFrontier.py를 실행시켰는데,

mk=Analyzer.MarketDB
stocks=['삼성전자', 'SK하이닉스', '현대자동차', 'NAVER']
df=pd.DataFrame()
for s in stocks:
    df[s] = mk.get_daily_price(s, '2016-05-05', '2018-04-27')['close']

에서

end_date is initialized to '2020-11-15'
  File "c:/Users/skwjd/OneDrive/문서/myPackage/8_EfficientFrontier.py", line 10, in <module>
    df[s] = mk.get_daily_price(s, '2016-05-05', '2018-04-27')['close']
  File "c:\Users\skwjd\OneDrive\문서\myPackage\Woo\Analyzer.py", line 78, in get_daily_price
    codes_keys=list(self.codes.keys())
AttributeError: 'str' object has no attribute 'codes'

라고 터미널에서 출력되었습니다. 

여기서 문제점은
1)  mk.get_daily_price(s, '2016-05-05', '2018-04-27')['close']에서 
analyzer.py 의 def get_daily_price(self, code, start_date=None, end_date=None)를 인식 잘못한 점.
(터미널에서는 end_date를 none으로 인식했습니다.)

2) 코드를 조금만 수정해서 get_daily_price함수 code인자에 code를 넣어도 
    codes_keys=list(self.codes.keys())
AttributeError: 'str' object has no attribute 'codes'
라는 에러창이 뜬다는 점입니다.

문제점과 해결방안을 알수 있을까요?

**Comment by INVESTAR** [comment]
안녕하세요. 김황후입니다.

mk = Analyzer.MarketDB()처럼 괄호()를 추가해 보시기 바랍니다.
코드에서 괄호가 빠져있을 경우, 동일하게 오류가 발생합니다.

mk = Analyzer.MarketDB
stocks = ['삼성전자', 'SK하이닉스', '현대자동차', 'NAVER']
df = pd.DataFrame()
for s in stocks:
    df[s] = mk.get_daily_price(s, '2016-01-04', '2018-04-27')['close']

================= RESTART: C:\myPackage\EffieientFrontier.py
=================
end_date is initialized to '2020-11-16'
Traceback (most recent call last):
  File "C:\myPackage\EffieientFrontier.py", line 10, in <module>
    df[s] = mk.get_daily_price(s, '2016-01-04', '2018-04-27')['close']
  File "C:\myPackage\Investar\Analyzer.py", line 75, in get_daily_price
    codes_keys = list(self.codes.keys())
AttributeError: 'str' object has no attribute 'codes'

감사합니다.
