### ISSUE TITLE
DBupdater.py pgrr return none

### ISSUE THREAD

**Issue by Chiral90** [INVESTAR/StockAnalysisInPython#17]
dbupdater가 동작하지 않습니다
def read_naver 에서 pgrr이 none을 반환하면서 막히기 시작합니다
네이버에서 일별 시세 페이지를 제대로 받아오지 못하는 것 같은데 무슨 문제인지 알고싶습니다.
어제까지는 잘 작동했습니다.
doc은 <http.client.HTTPResponse object at 0x05C34D30>를 반환하고
html은 페이지를 찾을 수 없다는 내용들이 뜨네요

**Comment by INVESTAR** [comment]
알려주셔서 감사합니다. 네이버 금융에서 User-agent 정보가 없는 웹 스크레이핑을 차단하여 발생한 현상으로, requests 라이브러리를 사용하도록 DBUpdater 코드를 수정하였습니다. 관련 내용은 Readme.md 파일을 참고하시기 바랍니다.
