### ISSUE TITLE
5.4. DBUpdater를 사용한다 해도 daily_price 테이블 업데이트가 안됩니다.

### ISSUE THREAD

**Issue by eugene-ryu** [INVESTAR/StockAnalysisInPython#173]
안녕하세요.

heidiDB도 켜놓고, VSCode에서 python DBUpdater.py 를 쳐서 업데이트도 해보고...
주피터 노트북으로 전체 .py 모듈들 전부 불러다가 해보기도 했습니다.

![Cap 2023-03-07 18-21-39-805](https://user-images.githubusercontent.com/92520641/223378863-961f397f-0d9f-498b-b941-4a680affc6b1.jpg)

아래 스샷처럼  df = pd.read_sql(sql, self.conn 부분만 나오고 나서, 이후에 데이터를 받아온다던가 하는 부분도 뜨지를 않습니다. company_info 테이블은 정상적으로 채워졌는데, daily_price만 채워지질 않으니 답답하네요.

![Cap 2023-03-07 18-23-32-369](https://user-images.githubusercontent.com/92520641/223379832-670d2093-6d4f-4a70-b0c5-bb6e9e02d0d0.png)

제가 만든 DB이름은 'investar'라서 다 이걸로 바꿔주고, 패스워드도 제대로 넣어주고, autocommit도 True로 설정해줬는데도 daily_price 이 테이블 채우는 일만 안되네요...

제 책은 4쇄본이구요. 혹시 errata 부분이나 수정할 부분이 있었는지.. 궁금합니다.

**Comment by naver0103** [comment]
DBUpdaterEX.py를 써도 code만 들어오는 데요.... 안되시는 분들 어떻게 해결하셨나요?

**Comment by naver0103** [comment]
> 안녕하세요.
> 
> heidiDB도 켜놓고, VSCode에서 python DBUpdater.py 를 쳐서 업데이트도 해보고... 주피터 노트북으로 전체 .py 모듈들 전부 불러다가 해보기도 했습니다.
> 
> ![Cap 2023-03-07 18-21-39-805](https://user-images.githubusercontent.com/92520641/223378863-961f397f-0d9f-498b-b941-4a680affc6b1.jpg)
> 
> 아래 스샷처럼 df = pd.read_sql(sql, self.conn 부분만 나오고 나서, 이후에 데이터를 받아온다던가 하는 부분도 뜨지를 않습니다. company_info 테이블은 정상적으로 채워졌는데, daily_price만 채워지질 않으니 답답하네요.
> 
> ![Cap 2023-03-07 18-23-32-369](https://user-images.githubusercontent.com/92520641/223379832-670d2093-6d4f-4a70-b0c5-bb6e9e02d0d0.png)
> 
> 제가 만든 DB이름은 'investar'라서 다 이걸로 바꿔주고, 패스워드도 제대로 넣어주고, autocommit도 True로 설정해줬는데도 daily_price 이 테이블 채우는 일만 안되네요...
> 
> 제 책은 4쇄본이구요. 혹시 errata 부분이나 수정할 부분이 있었는지.. 궁금합니다.

저는 6쇄본인데요....에러나는걸 어떻게 해결하셨나요?

**Comment by silvertaxi22** [comment]
저도 여기서 안됨 -_- 다운로드는 되는데 테이블 채우는게 안되고 있음...  ㅠㅠ 일단 배치사이즈 줄여서 테스트 하고 있는데, 잘 됐으면 좋겠음..

**Comment by naver0103** [comment]
해결했어요.내 Galaxy에서 보냄
-------- 원본 이메일 --------발신: silvertaxi22 ***@***.***> 날짜: 24/6/21  10:04  (GMT+09:00) 받은 사람: INVESTAR/StockAnalysisInPython ***@***.***> 참조: The man ***@***.***>, Comment ***@***.***> 제목: Re: [INVESTAR/StockAnalysisInPython] 5.4. DBUpdater를 사용한다 해도 daily_price 테이블 업데이트가 안됩니다. (Issue #173) 
저도 여기서 안됨 -_- 다운로드는 되는데 테이블 채우는게 안되고 있음...  ㅠㅠ 일단 배치사이즈 줄여서 테스트 하고 있는데, 잘 됐으면 좋겠음..
