### ISSUE TITLE
3/11부터 네이버 자료가 db에 저장이 안됩니다.

### ISSUE THREAD

**Issue by naver0103** [INVESTAR/StockAnalysisInPython#179]
잘되던 DB저장이 3/11부터는 안되고 있으니, 저자님께서는 검토바랍니다.
중간에 네이버금융에서 상승 하락에 대한 diff부분을 좀 만져서 그런건지...
아니면 lxml 쪽이 잘못된건지, 윗부분은 잘되는데, daily_price가 안됩니다.

**Comment by INVESTAR** [comment]
전일비 데이터(diff)에서 문자를 제외하고 숫자만 추출해서 처리하도록 DBUpdaterEx.py 코드를 수정하였으니 README.md를 참고하시기 바랍니다.
