### ISSUE TITLE
DBupdater.py 네이버에서 막은 거 같은데요 방법이 없을까요?

### ISSUE THREAD

**Issue by woodongho** [INVESTAR/StockAnalysisInPython#19]
안녕하세요 책 보고 열심히 이것저것 만들어서 투자 자동화에 많은 도움 받았습니다.
2021/1/7 저녁부터 업데이터가 작동하지 않아 확인해보니, 네이버 크롤링이 막힌 거 같습니다.
https://finance.naver.com/item/sise_day.nhn?code={code}
헤더를 넣어주면 에러는 뜨지 않지만, 표를 가져 오지는 못하는데, 어떻게 코드를 바꿔야 할까요? 이 책을 제대로 이용하려면, 네이버금융에서 시세정보를 가져와서 DB화해야 하는데 난감하네요. 대처방법 부탁드립니다.

**Comment by INVESTAR** [comment]
알려주셔서 감사합니다. 네이버 금융에서 User-agent 정보가 없는 웹 스크레이핑을 차단하여 발생한 현상으로, requests 라이브러리를 사용하도록 DBUpdater 코드를 수정하였습니다. 관련 내용은 Readme.md 파일을 참고하시기 바랍니다.
