### ISSUE TITLE
저도 DBUpdater.py 에서 네이버 정보를 못 가져 옵니다.

### ISSUE THREAD

**Issue by kflame71** [INVESTAR/StockAnalysisInPython#20]
저도 동일하게 오류가 발생하고 있어 원인을 찾다가 이곳에 와서 보니 다른 분들도 동일한 현상으로 이슈를 올렸네요.

html = BeautifulSoup(doc, "lxml")

이 부분에서 html 내용을 보면 아래와 같은 메시지가 나옵니다.

"방문하시려는 페이지의 주소가 잘못 입력되었거나,
		페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.
		입력하신 주소가 정확한지 다시 한번 확인해 주시기 바랍니다.
	
관련 문의사항은 고객센터에 알려주시면 친절히 안내해드리겠습니다. 감사합니다."

처리 방법이 나오면 공유를 부탁드립니다.

**Comment by INVESTAR** [comment]
알려주셔서 감사합니다. 네이버 금융에서 User-agent 정보가 없는 웹 스크레이핑을 차단하여 발생한 현상으로, requests 라이브러리를 사용하도록 DBUpdater 코드를 수정하였습니다. 관련 내용은 Readme.md 파일을 참고하시기 바랍니다.
