### ISSUE TITLE
웹 스크랩 관련 문의

### ISSUE THREAD

**Issue by pj0109** [INVESTAR/StockAnalysisInPython#23]
안녕하세요, 저자님 책으로 파이썬을 공부중인 독자입니다. 웹 스크랩핑 관련해서, 책 188쪽 4.4.3의 코드를 실습하였는데

AttributeError: 'NoneType' object has no attribute 'a'

와 같은 에러가 계속 발생했습니다. 철자나 페이지 소스 등은 다 확인했는데 코드를 실행하면 자꾸 에러가 발생해서.. 앞선 글을 보니
웹 스크래핑 차단 이슈가 있다고 하셨는데 그것과 관련이 있는것인지, 아니면 다른 해결방법이 있는 것인지 문의드립니다.

좋은 책 써주셔서 다시 한번 감사드리고, 날이 추운데 항상 건강 유의하시길 바랍니다.
감사합니다.

**Comment by INVESTAR** [comment]
안녕하세요. 김황후입니다. 

AttributeError: 'NoneType' object has no attribute 'a'
상기 오류는 네이버에서 웹 스크레이핑을 차단했기 때문에 발생하는 것으로 
읽어온 웹 페이지가 없기 때문에 a 태그를 찾지 못해서 발생하는 오류입니다.

네이버 금융에서 http 패킷 헤더에 브라우저 정보(User-Agent)가 존재하는지 체크하기 때문에
requests 라이브러리를 사용하여 웹 브라우저 정보를 보내도록 수정해야 합니다.
즉, 아래처럼 BeautifulSoup() 생성자에 넘겨주는 HTML 정보를
urlopen()으로 읽은 정보가 아닌 requests.get()으로 읽은 정보로 변경해 주시기 바랍니다.

import requests
url = f"http://finance.naver.com/item/sise_day.nhn?code=005930"
html = BeautifulSoup(requests.get(url, headers={'User-agent': 'Mozilla/5.0'}).text, "lxml")

5장에 나오는 DBUpdater.py도 코드 수정이 필요하며
변경된 코드는 깃헙에 올려둔 DBUpdaterEx.py를 참고하시기 바랍니다.
