### ISSUE TITLE
cp5 Analyzer.py 

### ISSUE THREAD

**Issue by est22** [INVESTAR/StockAnalysisInPython#25]
안녕하세요 .
본문 247-248쪽에 질문 드립니다.
일별 시세 조회 API 전체 소스코드를 실행하려 합니다. 가장 최근 수정본으로 헤더 추가 및 ```requests``` 라이브러리 추가 모두 완료하였고 코드는 복붙이라 수정한 것이 없습니다. 터미널으로 파이썬 쉘에 접속하여 다음과 같이 ```mk.get_daily_price('삼성전자','2019-09-30','2019.10.4')``` 라고 치면 결과값이 계속 아래와 같이 나옵니다.
**Empty DataFrame
Columns: [code, date, open, high, low, close, diff, volume]
Index: []**

```>>> mk.codes['018260']``` 라고 입력한 경우
**'삼성에스디에스'**
라고 잘만 뜨는데 무엇이 문제인지 궁금합니다.

**Comment by INVESTAR** [comment]
mk.get_daily_price('삼성전자','2019-09-30','2019.10.4')라고 호출했을 때 빈 DataFrame이 리턴된 것은 마리아디비에 2019-09-30 ~ 2019-10-04 기간에 해당하는 삼성전자 주식 데이터가 존재하지 않기 때문입니다.

get_daily_price()를 이용해서 주식 시세를 조회하려면 네이버 금융에서 웹 스크레이핑한 데이터를  마리아디비 내부에 저장해 둬야 하는데... 해당 작업이 진행되지 않은 것 같습니다. 아래와 같은 작업 순서 중에서 5번 작업이 잘 이루어졌는지 확인해 주시기 바랍니다.

① 마리아디비 설치
② Investar 데이터베이스 생성
③ pymysql 라이브러리 설치 
④ ch05_04_CreateTable.sql 쿼리를 실행해서 company_info, daily price 테이블 생성 
⑤ DBUpdaterEx.py를 실행하여 웹스크레이핑 한 주식 데이터를 마리아디비에 저장 

5번 작업을 진행했는데도 조회가 안된다면, 조회 기간을 최근 날짜로 변경해서 조회해 보시기 바랍니다.
참고로, 웹 스크레이핑 대상 기간을 늘여야 할 경우에는 config.json 파일의 pages_to_fetch 값을 높게 설정해 주시면 됩니다.

**Comment by est22** [comment]
감사합니다, config.json 파일을 변경하여 조회하니 되었습니다. :)
