### ISSUE TITLE
Select 쿼리문 작성시 오류

### ISSUE THREAD

**Issue by Planche-prog** [INVESTAR/StockAnalysisInPython#27]
connection =pymysql.connect(host='localhost', port=3306, db='INVESTAR', user='root', passwd='********', autocommit=True)
에서 문제가 발생되었는데

OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 99] Cannot assign requested address)")

라고 뜨네요 어떤 문제가 있는건가요?

**Comment by INVESTAR** [comment]
정확한 원인은 알 수 없지만 특정 프로그램에 의해서 TIME_WAIT 상태의 TCP 세션이 지속적으로 증가하면서
시스템이 MariaDB 접속에 필요한 포트를 할당할 수 없는 상태가 됐을 가능성이 있습니다.

https://stackoverflow.com/questions/24884438/2003-cant-connect-to-mysql-server-on-127-0-0-13306-99-cannot-assign-reques/27124742
https://cleanupthedesk.tistory.com/3 (한글)

위 내용에 따르면 Linux 환경에서는 TIME_WAIT 상태의 TCP 세션을 재사용하도록 설정할 수 있는 것 같은데
Windows에서는 시스템 설정을 변경하기 보다는 실제로 포트를 할당할 수 없게 된 원인을 찾아서
해당 원인을 제거하는 것이 바람직한 해결 방법이 될 것 같습니다.
