### ISSUE TITLE
변동성돌파전략 매매 수정에 관한 질문입니다.

### ISSUE THREAD

**Issue by buddykr** [INVESTAR/StockAnalysisInPython#29]
책에 나온것을 따라서 조금씩 배워보고 있습니다.

변동성 돌파전략에서 당일 전략 매도를 익일 시초가 매도로 바꾸려는데 넘 힘드네요.
ETF자동 매매에서 익일 시초가 일괄 매도로 변경 하려면 어떻게 코딩을 해야 할까요? ^^
도움을 주실 수 있을까 하고 여쭈어 봅니다.

**Comment by buddykr** [comment]
if t_9 < t_now < t_start and soldout == False:
                soldout = True
                sell_all()

이 조건문이 "9시에서 9시 15분 사이에 만약 남은 주식이 있다면 다 true 라고 하고
다 팔아라" 이런 것이죠?
그럼 뒤에오는
if t_sell < t_now < t_exit:  # PM 03:15 ~ PM 03:20 : 일괄 매도
               if sell_all() == True:
                  dbgout('`sell_all() returned True -> self-destructed!`')
                  sys.exit(0) 

를 주석 처리하면 가능 할것 같은데 맞나요? 궁금합니다 ^^

**Comment by INVESTAR** [comment]
장 시작 후 09:00 ~ 09:15 사이에 남은 주식을 모두 매도하려면 전반적인 흐름은 아래처럼 될 것 같습니다. 다만, 15:20 ~ 15:30 사이는 동시호가 시간이기 때문에 매수 주문은 가능하지만, 실제 주문 체결은 15:30에 이루어집니다. 따라서, 동시호가 시간에 대해서 매수 처리 로직을 추가로 개발하셔야 할 것 같습니다. 

```
if t_0900 < t_now < t_0915: 
  sell_all()

if t_0915 < t_now < t_1520 : 
  for sym in symbol_list:
    if len(bought_list) < target_buy_count:
      buy_etf(sym)
      time.sleep(1)
  if t_now.minute == 30 and 0 <= t_now.second <= 5:
    get_stock_balance('ALL')
    time.sleep(5)

if t_1520 < t_now < t_1530 : 
  pass

if t_1530 < t_now:
  dbgout('self-destructed!')
  sys.exit(0)
```
