### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'df'

### ISSUE THREAD

**Issue by Planche-prog** [INVESTAR/StockAnalysisInPython#30]
import pymysql

connection=pymysql.connect(host='localhost', port=3306,df='INVESTAR',
                           user='root', passwd='********', autocommit=True)

cursor=connection.cursor()
cursor.execute('SELECT VERSION();')
result=cursor.fetchone()

print('MariaDB version :{}'.format(result))
connection.close()

여기서
Traceback (most recent call last):
  File "C:\myPackage\_test_.py", line 4, in <module>
    user='root', passwd='1217chea', autocommit=True)
TypeError: __init__() got an unexpected keyword argument 'df'

라고 나오네요

인터넷에 검색해보니까
 autocommit=True 제거하라는 것 같아서 없앴는데도 효과가 없습니다.
어떻게 해야하는 지 알려주시면 안될까요?

(참고로 어제까지는 오류가 뜨지 않았습니다. heidisql에 접속하려할때도 Access denied for user 'root'@'localhost' (using password: YES) 라고 뜨네요)

이전까지는 괜찮았는데 파이썬데이터 응용부분 들어가면서 앞으로 나아갈 수 없는 벽을 느끼는 것 같습니다. 아마 기본기가 부족해서 그런 듯 한데 무엇부터 해야할지도 모르겠습니다.  조언부탁드립니다.

**Comment by INVESTAR** [comment]
TypeError: init() got an unexpected keyword argument 'df'
적어주신 오류 메시지를 보시면 예상치 못한 키워드 인자 df로 인해서 에러가 발생한 것으로 보입니다.

connection=pymysql.connect(host='localhost', port=3306,df='INVESTAR',
user='root', passwd='********', autocommit=True)
위 코드 중에서 df='INVESTAR' 인자를 db='INVESTAR' 로 수정하시기 바랍니다.
