### ISSUE TITLE
denied for user

### ISSUE THREAD

**Issue by Planche-prog** [INVESTAR/StockAnalysisInPython#33]
질문 계속 드려 번거로우실텐데 답변 성실히 해주셔서 감사합니다.
이거 하나 더 물어보겠습니다.

import pymysql

connection=pymysql.connect(host='localhost', port=3306,db='INVESTAR',
user='root', passwd='********', autocommit=True)

cursor=connection.cursor()
cursor.execute('SELECT VERSION();')
result=cursor.fetchone()

print('MariaDB version :{}'.format(result))
connection.close()

결과는
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")로 나옵니다.

또한
heidisql로 접속하려할 시 Access denied for user 'root'@'localhost' (using password: YES)로 똑같이 표시됩니다.
혹시 방법이 없을까요?

**Comment by INVESTAR** [comment]
https://giyatto.tistory.com/60

위의 블로그를 참고하셔서 비밀번호를 변경해 보시기 바랍니다. 
리눅스 환경을 기준으로 작성된 포스트이기 때문에, 윈도우에서는 아래와 같이 실행하셔야 할 것 같습니다.

```
C:\>cd "C:\Program Files\MariaDB 10.5\bin"
C:\Program Files\MariaDB 10.5\bin>mysql.exe -u root -p
```
