### ISSUE TITLE
파이썬 가상환경

### ISSUE THREAD

**Issue by Planche-prog** [INVESTAR/StockAnalysisInPython#37]
![image](https://user-images.githubusercontent.com/78189661/108005684-ab58bc00-703c-11eb-9db3-9fa3b102f5cd.png)

venv 가상환경 만든 후  파이썬 버전을 확인해보니 64비트 파이썬 버전이 표시됩니다. 어떻게 해결해야하나요?

**Comment by INVESTAR** [comment]
알려주신 정보만으로는 정확한 원인을 알 수 없지만
activate를 한 상태에서 64비트 파이썬이 실행되는 것으로 봐서는 
환경변수 또는 home 경로가 잘못됐을 가능성이 존재합니다.

C\VirtualEnv\Py380_32 디렉터리 밑에 pyvenv.cfg 설정 파일을 열어서 
home과 version의 값이 32비트 파이썬에 맞게 변경되어 있는지 확인해 보시고
설정 파일에도 문제가 없다면, 아래 순서대로 다시 한번 설치해 보시기 바랍니다.

① C:\VirtualEnv 디렉터리 삭제
② [제어판] > [시스템 환경 변수 편집]에서 Path 환경 변수에 설정된 파이썬 경로를 모두 삭제
③ [제어판] > [프로그램] > [프로그램 및 기능] > [프로그램 제거 또는 변경]에서 PC에 설치된 모든 Python 버전을 제거
④ 64비트 파이썬 설치 후 가상 환경에서 32비트 파이썬 설치
