### ISSUE TITLE
가상환경에서 pip

### ISSUE THREAD

**Issue by Planche-prog** [INVESTAR/StockAnalysisInPython#41]
tensorflow는 파이썬 버전 3.5~3.8까지 호환이 된다고 tensorflow사이트에 표시가 되어있습니다.

그래서 저는 파이썬 버전 3.8.0을 설치한 후 가상환경을 만들어서 밑에와 같이 tensorflow를 설치하려 했으나 실패했습니다.
어떤 것을 고쳐야 할까요?

![image](https://user-images.githubusercontent.com/78189661/108390014-930eba00-7253-11eb-9c6c-1b58e6fb8190.png)

**Comment by INVESTAR** [comment]
tensorflow2는 64비트만 지원하는 것 같습니다.
https://www.tensorflow.org/install?hl=ko
![tf](https://user-images.githubusercontent.com/17264597/108610568-dc106b00-7419-11eb-94a3-416bd18a0f84.jpg)

현재 사용하시는 가상환경은 32비트인 것 같은데 
64비트 파이썬 환경에서 pip install tensorflow 로 설치하시기 바랍니다.
