### ISSUE TITLE
질문 하나 드릴게요.

### ISSUE THREAD

**Issue by jnbatelier** [INVESTAR/StockAnalysisInPython#5]
책 보고 열심히 따라하는 중인데, 중간 쯤 되서 질문을 좀 드릴게요

`    def replace_into_db(self, df, num, code, company):

        """네이버에서 읽어온 주식 시세를 DB에 REPLACE"""
        with self.conn.cursor() as curs:
            for r in df.itertuples():
                sql = f"REPLACE INTO daily_price VALUES ('{code}', "\
                    f"'{r.date}', {r.open}, {r.high}, {r.low}, {r.close}, "\
                    f"{r.diff}, {r.volume})"
                curs.execute(sql)
            self.conn.commit()
            print('[{}] #{:04d} {} ({}) : {} rows > REPLACE INTO daily_'\
                'price [OK]'.format(datetime.now().strftime('%Y-%m-%d'\
                ' %H:%M'), num+1, company, code, len(df)))`

이 부분에서 책 설명에는 pandas 명령어인 to_sql 을 쓰는 방법도 있는데, 단순화를 위해서 위와 같이 사용한다고 했는데..
책에서 나온 설명처럼 db 안에 table 을 ticker 로 만들기 위해 to_sql 을 사용하고자 하는데.

TypeError: unhashable type: 'list'

가 계속 나옵니다. sqlite 을 사용시에는 잘 들어가는데, 마리아db 사용시 다른 방법이 필요한가요..?

**Comment by INVESTAR** [comment]
안녕하세요. 김황후입니다.

저도 처음에는 233페이지에서 언급한 것처럼 to_sql() 함수를 이용해서 구현하려고 했었으나,
to_sql() 함수는 테이블의 일부 행만 업데이트할 수 없고
데이터프레임을 테이블 하나로 저장하는 문제점이 있습니다.

현재 소스 코드는 REPLACE INTO 구문을 사용해서 특정 행들만 업데이트 하도록 개발되어 있는데
이를 to_sql() 함수를 사용하도록 변경하려면 코드 구조를 전반적으로 수정해야 합니다.

함수 단위만 수정하는 정도가 아니고 전체 소스 코드를 고쳐야 해서
to_sql() 함수로 변경하는 법을 알려드리는 것은  현실적으로 어려울 것 같습니다.

죄송합니다.
