### ISSUE TITLE
mplfinance 신형에서 한글 폰트 사용  문제

### ISSUE THREAD

**Issue by cahn70** [INVESTAR/StockAnalysisInPython#50]
mplfinance에서 아직 label 기능은 구현이 안되어 있는 것 같고, title만이라도 '삼성전자 캔들 차트' 처럼 한글로 넣어보려고 하는데 폰트 문제가 있다고 warning이 뜨네요.
 찾아보니 matplotlib에서 한글 폰트를 사용하려면 아래와 같이 폰트 설정을 해주면 된다고 해서 테스트 해보니, 일반적인 라인 그래프는 테스트 해보았을 때 title에 제대로 한글이 출력되어 나오는데, mplfinance로 그린 캔들챠트는 여전히 폰트 warning이 뜨면서 title에 한글이 제대로 나오지가 않네요.
무엇이 문제일까요?

from matplotlib import font_manager, rc
import platform

path = 'c:/Windows/Fonts/malgun.ttf'
font_name = font_manager.FontProperties(fname=path).get_name()
rc('font', family=font_name)

**Comment by INVESTAR** [comment]
현재 mplfinance의 깃허브(https://github.com/matplotlib/mplfinance )에 나와있는 가장 단순한 예제를 실행해봐도
아래처럼 오류가 나면서 실행이 안되네요. mplfinance 패키지 자체에 뭔가 문제가 있는 것 같은데... 
정상화가 될 때까지 좀 기다려봐야 할 것 같습니다.

AttributeError: partially initialized module 'mplfinance' has no attribute 'plot' (most likely due to a circular import)

**Comment by cahn70** [comment]
> 현재 mplfinance의 깃허브(https://github.com/matplotlib/mplfinance )에 나와있는 가장 단순한 예제를 실행해봐도
> 아래처럼 오류가 나면서 실행이 안되네요. mplfinance 패키지 자체에 뭔가 문제가 있는 것 같은데...
> 정상화가 될 때까지 좀 기다려봐야 할 것 같습니다.
> 
> AttributeError: partially initialized module 'mplfinance' has no attribute 'plot' (most likely due to a circular import)

**Comment by cahn70** [comment]
답변 감사합니다. 
일단 기다려 봐야겠네요...^^

**Comment by white-seolpyo** [comment]
matplotlib에서 기본으로 설정된 폰트의 문제로 [한글 폰트를 지원하는 font family를 설정하면](https://white.seolpyo.com/entry/134/?from=github) 한글이 정상적으로 출력됩니다.
