### ISSUE TITLE
8.2.2 크레온 플러스 자동접속 (p. 374)

### ISSUE THREAD

**Issue by hohohoohoho** [INVESTAR/StockAnalysisInPython#67]
안녕하세요,
우선,  좋은 책을 만들어 주셔서 감사드립니다. 

열심히 따라 하고 있는 중 문제가 발생해서 문의 드립니다. 
 
1. 발생 위치 :  8.2.2  크레온 플러스 자동접속 ( p. 374 )
2. 문제 :  32bit 를 activate 해서 'pywinauto' 패키지를 설치하였으나, 코드를 컴파일시 해당 모듈이 없다는 오류메시지 출력.

![image](https://user-images.githubusercontent.com/77595292/114299361-ac1a4580-9af5-11eb-8024-6a48a16da08f.png)

3. 진행환경 
  1) 2장의 32비트 파이썬 3.8 버전 (3.8.9) 버전 가상 환경 설치완료
  2) python.exe 와 pythonw.exe 파일의 '관리자 권한으로 실행' 설정 완료
  3) idle.pyw 는 '관리자 권한으로 실행' 설정 부분이 없어서, IDLE (Python 3.8.9 32bit)' 바로 가기 파일을 '관리자 권한으로 실행' 설 
      정 완료

4. 기타 
  1) 'VirtualEnv' 폴더에서 32bit를 activate 하고 'pywinauto' 패키지를 설치하였습니다.
![image](https://user-images.githubusercontent.com/77595292/114299408-eab00000-9af5-11eb-86c8-8544f2580dd1.png)
  2) 파일을 C:\VirtualEnv\Py389_32\Scripts\python.exe  으로 바로 실행을 진행하면 아래의 오류와 함께 접속은 됩니다. 
![image](https://user-images.githubusercontent.com/77595292/114299427-1501bd80-9af6-11eb-8f9c-71539c390266.png)

**Comment by INVESTAR** [comment]
아래 페이지를 참고해 보시기 바랍니다.
https://dojang.io/mod/page/view.php?id=2470

**47.11.7 가상 환경을 사용하는 IDLE 실행하기**
venv, conda 가상 환경을 사용하는 IDLE을 실행하려면 가상 환경을 활성화 시킨 뒤 idlelib 모듈을 실행하면 됩니다. 이렇게 하면 IDLE에서도 현재 가상 환경의 패키지를 사용할 수 있습니다.
```
C:\project\example>pythonw.exe -m idlelib
```

**Comment by hohohoohoho** [comment]
감사합니다.
