### ISSUE TITLE
챕터5 > DBUpdater.py

### ISSUE THREAD

**Issue by elf7979** [INVESTAR/StockAnalysisInPython#8]
안녕하세요
DBUpdater.py를 책에 있는대로 경로와 깃헙에서 파일을 다운받아서 실행했는데 daily_price에 저장된 데이터가 종목 당 10일치만 저장이 됩니다.

DBUpadter.py 설명을 보면 처음 모든 데이터를 저장하고 나서 10일치씩 업데이트 되는 구조인데, 마지막 페이지부터 모든 데이터가 저장되는 부분이 실행이 안 된것 같아요.

DBUpdater.py 파일을 열어서 수정해야 하는 부분이 있을까요?

--------------------------------------------------------------------------------------------------------------------------------------------

책에 나오는 내용대로 config.json 파일을 검색해서 메모장으로 열고 페이지수를 100으로 바꾸고 저장하니 100 page로 저장이 됩니다. 모든 종목별로 100 page 저장하고 나면 config 파일을 다시 수정하면 될 것 같습니다

**Comment by elf7979** [comment]
안녕하세요.
바쁘시겠지만 제가 프로그래밍에 익숙하지 않아서 다시 질문 드립니다

config.json 파일에서 fetch note : 100으로 수정해서 처음에 4년 정도의 데이터를 다 다운 받았습니다.
그 후, config.json 파일에서 다시 fetch note : 10으로 수정했습니다.

그리고 python c:\myPackage\Investar\DBUpdater.py 파일을 실행했는데,
처음에 replace into table이 빠르게 지나가서 업데이트 되는 줄 알았는데

다시 처음부터 downloading 1 ~ 100 page가 나와서 일단 창을 닫았습니다.
위의 명령어를 다시 실행한 건 레지스터리에 등록했지만 자동으로 DBUpdater 파일이 실행되지 않아서 수동으로 실행했습니다

어떻게 하면 100 페이지 다운받은 시점에서 그 다음 일자부터 db에 추가해서 업데이트 할 수 있을까요?

**Comment by INVESTAR** [comment]
안녕하세요. 김황후입니다.
제가 주말에 개인적으로 일이 좀 있어서 답변이 좀 늦어졌습니다.

config.json 파일에서 fetch note : 100으로 수정해서 처음에 4년 정도의 데이터를 다 다운 받았습니다.
그 후, config.json 파일에서 다시 fetch note : 10으로 수정했습니다.

> 만일 10페이지씩 가져오도록 config.json 파일을 수정했다면, 10페이지만 가져와야 정상입니다.

   아래 DBUpdater에서  페이지를 읽어오는 코드를 보시면,
        try:
            with open('config.json', 'r') as in_file:
                config = json.load(in_file)
                pages_to_fetch = config['pages_to_fetch']
        except FileNotFoundError:
            with open('config.json', 'w') as out_file:
                pages_to_fetch = 100
                config = {'pages_to_fetch': 1}
                json.dump(config, out_file)

  처음 실행 시에는 100 페이지로 처리하고, 파일에는 1로 저장해 놓습니다.
  따라서 DBUpdater는 최초 실행 시에는 100페이지를, 그 이후부터는 1페이지씩 가져옵니다.
  만일 사용자가 수동으로 config.json파일에서 pages_to_fetch 값을 10으로 변경했다면,
  그 이후부터는 10페이지씩 읽어오는 게 정상입니다.

  아래는 실제로 제가 운영하고 있는 윈도우 서버에 설정되어 있는 config.json 파일을 캡처한 그림입니다.
  저는 별도로 페이지 값을 수정하지 않았기 때문에 1페이지씩 가져오는 것으로 자동 변경되어 있습니다.

   [image: capture1_configjson.jpg]


그리고 python c:\myPackage\Investar\DBUpdater.py 파일을 실행했는데,
처음에 replace into table이 빠르게 지나가서 업데이트 되는 줄 알았는데

다시 처음부터 downloading 1 ~ 100 page가 나와서 일단 창을 닫았습니다.

>  DBUpdater.py의 실행 경로가 달라질 경우, 해당 디렉터리에 config.json 파일이 존재하지 않았다면

    100 페이지로 불러왔을 가능성이 있습니다.


    DBUpdater.py는 자신이 위치한 디렉터리에 존재하는 config.json 파일을 찾기 때문에

   실행하는 DBUpdater.py의 위치가 달랐던 것이 아닌지 확인해야 할 것 같습니다.


위의 명령어를 다시 실행한 건 레지스터리에 등록했지만 자동으로 DBUpdater 파일이 실행되지 않아서 수동으로 실행했습니다

>  V3 등의 보안 프로그램이 간혹 run 레지스트리에 등록된 프로그램을 자동 실행되지 않도록 막는 경우가 있습니다.

    그럴 때에는 자동매매 챕터를 참고하셔서, 윈도우 스케줄러를 이용해서 자동 실행되도록 하셔야 합니다.


어떻게 하면 100 페이지 다운받은 시점에서 그 다음 일자부터 db에 추가해서 업데이트 할 수 있을까요?

> DBUpdater.py에서 1페이지를 가져온다는 것은

  오늘을 기준으로 네이버 일별 시세를 1페이지(10일치 데이터) 가져온다는 의미입니다.

  이미 100페이지(1000일치=약 4년)를 다운로드 받으셨다면

  config.json의 pages_to_fetch 값이 1로 자동 변경되기 때문에

  오늘을 기준으로 10일 전까지의 데이터를 가져와서 DB에 업데이트 합니다.

[image: capture2_1page.jpg]
실제로 DBUpdater의 실행 결과를 봐도, 오늘로부터 1페이지 데이터만 가져오기 때문에
10 rows 즉 오늘부터 열흘치 이전까지의 데이터만 업데이트 하는 것을 알 수 있습니다.

[image: capture3_10rows.jpg]

감사합니다.
