### ISSUE TITLE
32비트 파이썬 venv 설치 시 pyvenv.cfg설정파일 인식 불가 문제. 

### ISSUE THREAD

**Issue by ChloeCYJ** [INVESTAR/StockAnalysisInPython#83]
VENV - HOME 인식 불가 문제

32비트 파이썬 3.8.0 설치 후에 venv 설치하고 pyvenv.cfg파일 home과 version정보를 32비트 경로(절대경로로 입력), 버전으로 설정해두었습니다.
그 이후 venv 활성화해서 python --version 커맨드를 치면 기존에 사용하고 있던 64비트 버전 (3.6.5)로 나옵니다.
설정파일을 인식하지 못하는 것같은데 해결방안 문의 드립니다.

===========================================

venv경로 : D:\Dev_Application\VitualEnv\Py380_32\pyvenv.cfg

[pyvenv.cfg]
home = D:\Dev_InstallFile\Python38-32    //32비트 설치경로
include-system-site-packages = false
version = 3.8.0

**Comment by INVESTAR** [comment]
① 파이썬 3.8.0 32비트 설치 
② D:\Dev_Application\VirtualEnv 디렉터리에서 python -m venv Py380_32 실행
③ D:\Dev_Application\VirtualEnv\Py380_32\pyenv.cfg 파일에서 home과 version 정보를 3.8.0 기준으로 수정
④ D:\Dev_Application\VirtualEnv\Py380_32\Scripts\activate.bat 실행 

32비트 파이썬 3.8.0을 설치한 후 venv를 설치했다고 하셨는데
그것이 ②처럼 venv를 실행했다는 의미라면
진행 과정이나 순서에서 잘못된 부분은 없어 보입니다.

혹시 모르니, ③의 pyenv.cfg 파일을 열어서 home 디렉터리 경로를 Ctrl+C로 복사하신 뒤에
캐맨드 창에서 cd 명령 뒤에 Ctrl+V로 붙여넣기해보시고
D:\Dev_InstallFile\Python38-32 디렉터리에 실제로 파이썬 3.8.0 32비트가 설치되어 있는지 확인해 보시기 바랍니다.

**Comment by ChloeCYJ** [comment]
안내주신 내용대로 동일하게 진행하고 삭제 후 재설치했는데도 여전히 3.6.5로 인식합니다. 
제 PC 설정과, 순서는 아래와 같이 진행했었습니다. 추가로 스크린샷도 같이 첨부하니 잘못된 부분이 있으면 안내 부탁드립니다.

1. 파이썬 3.8.0 32비트 설치
![image](https://user-images.githubusercontent.com/40730889/121127932-81ced500-c865-11eb-89a4-bd8dc8e140fa.png)

2. D:\Dev_Application\VirtualEnv 디렉터리에서 python -m venv Py380_32 실행

3. D:\Dev_Application\VirtualEnv\Py380_32\pyenv.cfg 파일에서 home과 version 정보를 3.8.0 기준으로 수정
![image](https://user-images.githubusercontent.com/40730889/121128035-b2167380-c865-11eb-8bcf-f987983274fd.png)

4. 32비트 설치된 경로 확인
![image](https://user-images.githubusercontent.com/40730889/121128200-fb66c300-c865-11eb-8695-6e0dde8b1251.png)

5. D:\Dev_Application\VirtualEnv\Py380_32\Scripts\activate.bat 실행 (버전확인 및 블록체인 라이브러리 설치)
![image](https://user-images.githubusercontent.com/40730889/121128515-7af49200-c866-11eb-850e-3be62b8d63bf.png)
- 3.8.0 인식x
- pip 라이브러리 설치 시 에러
- 환경 path는 추가하지 않았습니다.

**Comment by INVESTAR** [comment]
캡처하신 내용 중에는 틀린 부분은 없어보입니다.
동일한 방법으로 다른 PC에서 해보시면 아마 잘 되실 겁니다.

명령 프롬프트에 (Py380_32)가 표시된 것으로 봐서는 activate는 된 것 같은데 
실제로 python 버전은 3.6.5로 표시되고, Py_Initialize에서 오류가 나는 것으로 봐서 
환경 변수가 꼬였거나 뭔가 잘못된 부분이 있을 것 같습니다.

만일 저라면, 32비트 파이썬 3.8.0과 64비트 파이썬 3.6.5를 제거한 후
환경 변수에서 파이썬과 관련된 모든 경로들을 모두 삭제한 후 
처음부터 다시 64비트 파이썬 3.6.5를 설치한후 venv로 32비트 파이썬 3.8.0을 설치해 보겠습니다.

**Comment by ChloeCYJ** [comment]
여러버전을 설치하여 변수가 꼬였던 것 같습니다. 모두 삭제하고 새로 진행하니 오류없이 진행됩니다. 해결되었습니다.
